# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
 - init: 'composer create-project laravel/laravel laravel' # runs during prebuild
 - init: 'composer require spipu/html2pdf'
   command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - felixfbecker.php-debug
